variables:
  LUIGI_IMAGE: $CI_REGISTRY_IMAGE/luigi
  WEB_IMAGE: $CI_REGISTRY_IMAGE/web

before_script:
  - make -e login

stages:
  - build
  - push
  - deploy

build-luigi:
  stage: build
  script:
    - make -e build-luigi

build-web:
  stage: build
  script:
    - make -e build-web

push-web:
  stage: push
  script:
    - make -e push-web

push-luigi:
  stage: push
  script:
    - make -e push-luigi
  
deploy:
  stage: deploy
  environment: test
  script:
    - make -e deploy
  only:
    - master