stages:
  - push
  - deploy
  - clean

before_script:
  - make -e login

stages:
  - push
  - deploy
  - clean

.image: &image_definition
  stage: push
  script:
    - make -e push-latest
  only:
    - tags
    - triggers

push-latest:
  <<: *image_definition
  variables:
    PYTHON_VERSION: latest
  only:
    - tags
    - triggers

deploy:
  stage: deploy
  environment: production
  script:
    - make -e deploy
  only:
    - tags
    - triggers
clean :
  stage: clean
  script:
    - make -e clean
  when: manual
