version: '2'

services:
  sefarad:
    build: .
    image: registry.cluster.gsi.dit.upm.es/sefarad/dashboard-reddit
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    environment:
     - ES_ENDPOINT_EXTERNAL=${ES_ENDPOINT_EXTERNAL}
     - FUSEKI_ENDPOINT_DASHBOARD=${FUSEKI_ENDPOINT_DASHBOARD}
    networks:
      - sefarad-network

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - 'http.cors.allow-origin=*'
    volumes:
      - esdata:/usr/share/elasticsearch/data/

    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - sefarad-network


  fuseki:
    image: stain/jena-fuseki
    ports:
      - "13030:3030"
    volumes:
     - ./fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=${FUSEKI_PASSWORD}
    networks:
      - sefarad-network

  luigi:
    build: ./luigi/
    image: registry.cluster.gsi.dit.upm.es/sefarad/gsicrawler/
    volumes:
      - ./luigi:/usr/src/app
    ports:
      - "8082:8082"
    networks:
      - sefarad-network
    environment:
      - ES_ENDPOINT=${ES_ENDPOINT}
      - ES_PORT=${ES_PORT}
      - FUSEKI_ENDPOINT_EXTERNAL=${FUSEKI_ENDPOINT_EXTERNAL}
      - API_KEY_MEANING_CLOUD=${API_KEY_MEANING_CLOUD}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}

    depends_on:
      - elasticsearch

networks:
  sefarad-network:
    driver: bridge

volumes:
  esdata:
