version: '2'

services:
  web:
    build: .
    image: registry.cluster.gsi.dit.upm.es/sefarad/gsicrawler/web
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    networks:
      - sefarad-network
    environment:
      - LUIGI_ENDPOINT_EXTERNAL=${LUIGI_ENDPOINT_EXTERNAL}
      - ES_ENDPOINT_EXTERNAL=${ES_ENDPOINT_EXTERNAL}
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    ports:
      - "19200:9200"
      - "19300:9300"
    volumes:
      - ./elasticsearch/nodes:/usr/share/elasticsearch/data/nodes
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - sefarad-network

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "13030:3030"
    environment:
      - ADMIN_PASSWORD=${FUSEKI_PASSWORD}
    networks:
      - sefarad-network

  luigi:
    build: ./luigi/
    image: registry.cluster.gsi.dit.upm.es/sefarad/gsicrawler/luigi
    volumes:
      - ./luigi:/usr/src/app
    ports:
      - "18000:8000"
      - "8082:8082"
    networks:
      - sefarad-network
    environment:
      - REDDIT_CLIENT=${REDDIT_CLIENT}
      - REDDIT_TOKEN=${REDDIT_TOKEN}
      - REDDIT_PASS=${REDDIT_PASS}
      - REDDIT_USER=${REDDIT_USER}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - ES_ENDPOINT=${ES_ENDPOINT}
      - ES_PORT=${ES_PORT}
      - FUSEKI_ENDPOINT_EXTERNAL=${FUSEKI_ENDPOINT_EXTERNAL}

    depends_on:
      - elasticsearch


networks:
  sefarad-network:
    driver: bridge
