version: '2'

services:
  web:
    build: .
    image: registry.cluster.gsi.dit.upm.es/sefarad/gsicrawler/web
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    networks:
      - sefarad-network
    depends_on:
      - elasticsearch
    environment:
      - LUIGI_ENDPOINT_EXTERNAL=localhost:18000
      - ES_ENDPOINT_EXTERNAL=localhost:19200

  elasticsearch:
    image: elasticsearch
    ports:
      - "19200:9200"
      - "19300:9300"
    volumes:
      - ./elasticsearch/nodes:/usr/share/elasticsearch/data/nodes
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - sefarad-network

  luigi:
    build: ./luigi/
    image: registry.cluster.gsi.dit.upm.es/sefarad/gsicrawler/luigi
    volumes:
      - ./luigi:/usr/src/app
    ports:
      - "18000:8000"
      - "8082:8082"
    env_file:
      - .env
    networks:
      - sefarad-network
    depends_on:
      - elasticsearch


networks:
  sefarad-network:
    driver: bridge
