version: '2'

services:
  sefarad:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    networks:
      - sefarad-network
    depends_on:
      - elasticsearch
    environment:
      - LUIGI_ENDPOINT=localhost:8000
      - ES_ENDPOINT=localhost:9200

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/nodes:/usr/share/elasticsearch/data/nodes
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - sefarad-network

  luigi:
    build:
      context: luigi/
    volumes:
      - ./luigi:/usr/src/app
    ports:
      - "8082:8082"
      - "8000:8000"
    networks:
      - sefarad-network
    environment:
      - ES_ENDPOINT=elasticsearch
      - ES_PORT=9200
    depends_on:
      - elasticsearch


networks:
  sefarad-network:
    driver: bridge