---
apiVersion: v1
kind: Service
metadata:
  name: gsicrawler-web
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
  selector:
    role: gsicrawler-web
---
apiVersion: v1
kind: Service
metadata:
  name: gsicrawler-luigi
spec:
  type: ClusterIP
  ports:
    - name: luigiproxy
      port: 8000
      protocol: TCP
    - name: luigiweb
      port: 8082
      protocol: TCP
  selector:
    role: gsicrawler-luigi