---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gsicrawler-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: $CRAWLER_ENDPOINT_EXTERNAL
    http:
      paths:
      - path: /
        backend:
          serviceName: $CRAWLER_ENDPOINT
          servicePort: 8080
  - host: $LUIGI_ENDPOINT_EXTERNAL
    http:
      paths:
      - path: /
        backend:
          serviceName: $LUIGI_ENDPOINT
          servicePort: 8000
      - path: /tasks/
        backend:
          serviceName: $LUIGI_ENDPOINT
          servicePort: 8082
