---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gsicrawler-config
data:
    ES_ENDPOINT: "$ES_ENDPOINT"
    ES_PORT: "$ES_PORT"
    TWITTER_CONSUMER_KEY: "$TWITTER_CONSUMER_KEY"
    TWITTER_CONSUMER_SECRET: "$TWITTER_CONSUMER_SECRET"
    TWITTER_ACCESS_TOKEN: "$TWITTER_ACCESS_TOKEN"
    TWITTER_ACCESS_TOKEN_SECRET: "$TWITTER_ACCESS_TOKEN_SECRET"
    FUSEKI_ENDPOINT: "$FUSEKI_ENDPOINT"
    FUSEKI_PORT: "$FUSEKI_PORT"
    API_KEY_MEANINGCLOUD: "$API_KEY_MEANINGCLOUD"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: gsicrawler-luigi
        app: ${NAME}
    spec:
      containers:
      - name: gsicrawler
        image: ${CI_REGISTRY_IMAGE}:${VERSION}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
          - name: luigiweb
            containerPort: 8082
        envFrom:
        - configMapRef:
            name: gsicrawler-config

