---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${NAME}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: $LUIGI_ENDPOINT_EXTERNAL
    http:
      paths:
      - path: /tasks/
        backend:
          serviceName: $LUIGI_ENDPOINT
          servicePort: 8082
