---
apiVersion: v1
kind: Service
metadata:
  name: gsicrawler-latest
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
    - port: 8000
      protocol: TCP
    - port: 9200
      protocol: TCP
  selector:
    role: gsicrawler-latest
